# Generated by Django 2.2.7 on 2019-12-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='role_resource',
        ),
    ]
