# Generated by Django 2.2.7 on 2019-12-14 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Roles', '0001_initial'),
        ('Users', '0002_delete_role_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roles.Roles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
        migrations.RemoveField(
            model_name='role_action',
            name='action_id',
        ),
        migrations.RemoveField(
            model_name='role_action',
            name='role_id',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='role_action',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
